import { AuthenticationController } from '@src/modules/auth/controllers/AuthenticationController';
import { requestMock } from '@mocks/express/requestMock';
import { responseMock } from '@mocks/express/responseMock';
import { ClientAuthService } from '@src/modules/auth/services/interfaces/ClientAuthService';
import { ClientAuthMock } from '@mocks/modules/auth/services/ClientAuthMock';
import { GenerateTokenService } from '@src/modules/auth/services/interfaces/GenerateTokenService';
import { GenerateTokenMock } from '@mocks/modules/auth/services/GenerateTokenMock';
import { AuthInfo } from '@src/modules/auth/services/interfaces/AuthInfo';

const clientAuthService: ClientAuthService = new ClientAuthMock();
const generateTokenService: GenerateTokenService = new GenerateTokenMock();
const authenticationController: APIController = new AuthenticationController(
  clientAuthService,
  generateTokenService
);

const token = 'token';
const email = 'test@mail.com';
const password = 'test-password';

requestMock.body = {
  email,
  password
};

const authInfo: AuthInfo = {
  userId: '1',
  authAt: new Date()
};

describe('AuthenticationController', () => {
  beforeAll(() => {
    jest.useFakeTimers();
    jest.setSystemTime(new Date('13-06-2022'));
  });

  beforeEach(() => {
    jest.spyOn(clientAuthService, 'execute').mockResolvedValue(authInfo);
  });

  it('should return a response with a token and a message', async () => {
    await authenticationController.execute(requestMock, responseMock);

    expect(responseMock.status).toHaveBeenCalledWith(200);
    expect(responseMock.json).toHaveBeenCalledWith({
      success: true,
      message: 'Authentication successful.',
      data: token
    });
  });

  it('should get AuthInfo object from clientAuthService', async () => {
    jest.spyOn(clientAuthService, 'execute');

    await authenticationController.execute(requestMock, responseMock);

    expect(clientAuthService.execute).toHaveBeenCalledWith({
      email,
      password
    });
  });

  it('should call generateTokenService with AuthInfo object', async () => {
    jest.spyOn(generateTokenService, 'execute');

    await authenticationController.execute(requestMock, responseMock);

    expect(generateTokenService.execute).toHaveBeenCalledWith(authInfo);
  });

  it('should return token generated by generateTokenService', async () => {
    jest
      .spyOn(generateTokenService, 'execute')
      .mockResolvedValue(`test-${token}`);

    await authenticationController.execute(requestMock, responseMock);

    expect(responseMock.json).toHaveBeenCalledWith({
      success: true,
      message: 'Authentication successful.',
      data: `test-${token}`
    });
  });
});
