/users:
  post:
    description: Create a new user
    tags: [Users]
    requestBody:
      name: CreateUserDTO
      description: The user to create.
      required: true
      content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDTO'
    responses:
      201:
        $ref: '#/components/responses/ResourceCreated'
      400:
        $ref: '#/components/responses/InvalidInput'
      409:
        $ref: '#/components/responses/Conflict'
      500:
        $ref: '#/components/responses/ServerInternalError'

  get:
    description: Get all users
    tags: [Users]
    responses:
      200:
        description: Users fetched successfully.
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                message:
                  type: string
                  example: Users fetched successfully.
                data:
                  type: array
                  items:
                    $ref: '#/components/schemas/User'
      204:
        description: No users found.
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                message:
                  type: string
                  example: No users found.
                data:
                  type: object
                  nullable: true
                  example: null
      500:
        $ref: '#/components/responses/ServerInternalError'

/users/{userId}:
  get:
    description: Get data from a specific user
    tags: [Users]
    parameters:
      - in: path
        name: userId
        description: The user id.
        schema:
          $ref: '#/components/schemas/UserId'
    responses:
      200:
        description: User fetched successfully.
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                message:
                  type: string
                  example: User fetched successfully.
                data:
                  $ref: '#/components/schemas/User'
      404:
        $ref: '#/components/responses/NotFound'
      500:
        $ref: '#/components/responses/ServerInternalError'

  delete:
    description: Delete a user.
    security:
      - bearerAuth: []
    tags: [Users]
    parameters:
      - in: path
        name: userId
        description: The user id.
        schema:
          $ref: '#/components/schemas/UserId'
    responses:
      200:
        description: User deleted successfully.
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                message:
                  type: string
                  example: User deleted successfully.
                data:
                  type: object
                  nullable: true
                  example: null
      401:
        $ref: '#/components/responses/Unauthorized'
      404:
        $ref: '#/components/responses/NotFound'
      500:
        $ref: '#/components/responses/ServerInternalError'

  put:
    description: Update a user.
    security:
      - bearerAuth: []
    tags: [Users]
    requestBody:
      name: UpdateUserDTO
      description: The user updated data.
      required: true
      content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserDTO'
    parameters:
      - in: path
        name: userId
        description: The user id.
        schema:
          $ref: '#/components/schemas/UserId'
    responses:
      200:
        description: Users updated successfully.
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                message:
                  type: string
                  example: User updated successfully.
                data:
                  type: object
                  nullable: true
                  example: null
      400:
        $ref: '#/components/responses/InvalidInput'
      401:
        $ref: '#/components/responses/Unauthorized'
      404:
        $ref: '#/components/responses/NotFound'
      409:
        $ref: '#/components/responses/Conflict'
      500:
        $ref: '#/components/responses/ServerInternalError'

/users/{authorId}/posts:
  get:
    description: Get data from a specific user
    tags: [Users]
    parameters:
      - in: path
        name: authorId
        description: The posts author id. It is a user id.
        schema:
          $ref: '#/components/schemas/UserId'
    responses:
      200:
        description: User posts fetched successfully.
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                message:
                  type: string
                  example: User posts fetched successfully.
                data:
                  type: array
                  items:
                    $ref: '#/components/schemas/Post'
      404:
        $ref: '#/components/responses/NotFound'
      500:
        $ref: '#/components/responses/ServerInternalError'
