version: '3'
services:
  app:
    env_file:
      - ../.env
    build:
      context: .
      dockerfile: Dockerfile
    hostname: devcontainer
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      # Persist devcontainer's zsh history
      - app-zsh_history:/home/dev/.commandhistory
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    # ports:
    #   - "3030:3030"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
volumes:
  app-zsh_history:
